Add Hello World text on patient info screen to create a simple commit…
alexishamrak/capstone-desktop pull request #1
Opened 2023-01-17 23:02 UTC by julien-campbell

… to setup my branch

Creating this pull request as a sample of what I will do in the future. Was the way I've setup my branch and created my pull request correct?

2023-01-18 01:47 UTC, alexishamrak submitted a review, later dismissed
Looks good, branching is good too!

2023-01-24 04:02 UTC, alexishamrak requested changes

2023-01-24 04:02 UTC, alexishamrak commented on lib/screens/patient_info_screen.dart
> +                      Navigator.pushReplacement(
should use push instead of pushReplacement (this will automatically include a back button so you can navigate back to this screen when you are finished on the other one)

2023-01-24 04:02 UTC, alexishamrak commented on lib/widgets/dashed_separator.dart
> +class MySeparator extends StatelessWidget {
class name should match same as file name (whichever is easier to change)

2023-01-24 04:02 UTC, alexishamrak commented on lib/screens/patient_info_screen.dart
> +          body: Padding(
Using sized boxes and set font sizes doesn't work in scaling the app to different screen sizes. We will need to change this so that the font size and spacing adapts based on the screen size (there's tutorials on this but I can also help if needed)

2023-01-24 04:02 UTC, alexishamrak commented on lib/widgets/dashed_separator.dart
> +        final boxWidth = constraints.constrainWidth();
This widget seems to be adaptive, all should be good for this one

2023-01-24 04:02 UTC, alexishamrak commented on pubspec.yaml
> +  - family: Bitter
spacing does not match the above; this means the font won't necessarily be implemented by all machines (indent the family by one tab and adjust the rest accordingly)

2023-01-24 04:02 UTC, alexishamrak commented on pubspec.yaml
> +  - family: Merriweather
same comment as above

2023-01-26 21:22 UTC, julien-campbell commented on lib/screens/patient_info_screen.dart
> +          body: Padding(
I have resolved the rest of the comments, is it okay we update this later and merge for now?

2023-03-13 15:34 UTC, alexishamrak approved these changes

2023-03-13 15:34 UTC, merged